---
- hosts: all
  #gather_facts: no
  connection: local
  
  tasks:
  - name: take backup for fmc
    command: "show version"
    register: output
    vars:
     ansible_user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
     ansible_ssh_pass: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
     ANSIBLE_HOST_KEY_CHECKING: False
